### ISSUE TITLE
Unstable Behavior in MoG Example

### ISSUE THREAD

**Issue by jakevdp** [pymanopt/pymanopt#20] opened 2016-03-11 22:36 UTC
Hi – this looks like a really useful package: thanks for putting it together! I'm working through the [MoG example notebook](https://github.com/pymanopt/pymanopt/blob/master/examples/MoG.ipynb) to try to understand the package, and I'm finding that the optimization is very unstable: sometimes it converges in 1 iteration to a very poor result, sometimes it converges in 200+ iterations to a very good result, and sometimes it fails with a linear algebra error (singular matrix) in the Cholesky decomposition within ``manifolds/psd.py``.

Any thoughts on how to make this more stable? Do you think this is mainly an initialization issue?

**Comment by j-towns** [comment] 2016-03-12 03:01
Hi Jake

Thanks for the email. I've also encountered this issue and not sure what's causing it but I have a slight suspicion it might be a bug in the code, need to investigate. I'll let you know if/when I work out what the cause is.

Jamie

**Comment by jakevdp** [comment] 2016-03-12 04:21
Appreciate it – thanks! I'm pretty excited by the prospect of being able to fit a GMM-type model without having to rely on E-M. I've found them very useful on several occasions, and the manifold optimization approach looks very promising.

**Comment by j-towns** [comment] 2016-03-12 14:24
Note you can also do it using standard (not manifold) optimization if you parameterize the covariance matrices by their Cholesky decomposition - see https://github.com/HIPS/autograd/blob/master/examples/gmm.py

**Comment by sweichwald** [comment] 2016-03-14 15:43
Hi Jake -- Thanks for giving our toolbox a shot and taking a close look at the example!

The `convergence' after only 1 iteration boiled down to a bug which should be fixed now.

When fitting a MoG model a singular matrix can occur if a Gaussian component collapses onto one data point. One common way to deal with this is to reset those collapsing components (cf. e.g. p. 434 in Bishop, C. M. ``Pattern Recognition and Machine Learning.'' 2001). In Pymanopt an extended linesearcher can be passed to the SteepestDescent solver that detects close to singular covariance matrices and resets the corresponding components -- we will make an implementation of this idea available soon.

If you have encountered any further problems not related to one of the ones above, please just let us know.

Cheer, Sebastian.

**Comment by jakevdp** [comment] 2016-03-14 16:03
Thanks @j-towns and @sweichwald!

Quick question while I have your ear: from a quick reading of the Hosseini and Sra paper, it sounds like the Riemannian optimization approach actually makes this a convex problem on the manifold, so that the result will not be fooled by local optima like with the E-M or non-manifold direct optimization approaches. Am I understanding that correctly?

**Comment by j-towns** [comment] 2016-03-14 16:21
Unfortunately no, I also got that impression when I first read the paper. However, the result that your refering to only applies to a _single_ multivariate gaussian (i.e. not a mixture of gaussians). Their argument is that if the optimization is convex for a single gaussian then it's generalisation to a mixture should be better. But I think this is just an intuitive idea and is not proved rigorously.

**Comment by sweichwald** [comment] 2016-03-14 16:32
Some intuition as to why convexity breaks for an actual mixture of Gaussians: reordering of the components leaves the log-likelihood unchanged.

**Comment by sweichwald** [comment] 2016-03-14 20:14
Refer to 34f6b53 for the MoG example implementation that relies on an extended linesearcher to reset collapsed Gaussians in order to avoid singular matrices.

PositiveDefinite's retr/expm is numerically more stable now to avoid walking off the manifold and the `convergence' after 1 iteration bug is fixed.

**Closed by sweichwald** 2016-03-14 20:14 UTC

**Comment by jakevdp** [comment] 2016-03-14 21:18
Thanks!
